services:
  server:
    build: ./server
    command: npm run dev
    develop:
      watch: 
        - action: sync
          path: ./server
          target: /server
          ignore: 
            - node_modules/
        - action: rebuild
          path: ./server/package.json
    ports:
      - 5000:5000
  
  client:
    build: ./client
    command: npm run dev-exposed
    develop:
      watch: 
        - action: rebuild
          path: ./server/package.json
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/client:delegated
      - /client/node_modules/
    ports:
      - 3000:3000