<<<<<<< HEAD
version: '1'

=======
>>>>>>> pre-alpha/v1.0.0-gideon
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
<<<<<<< HEAD
      - "8000:8000"
=======
      - 8000:8000
>>>>>>> pre-alpha/v1.0.0-gideon
